[client]
remote_addr = "localhost:2333"
default_token = "123"

[client.transport]
type = "tls"
[client.transport.tls]
trusted_root = "examples/tls/ca-cert.pem"
hostname = "0.0.0.0"

[client.services.foo1]
local_addr = "127.0.0.1:80"
